apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfa-project-keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:18.0.2
        ports:
        - containerPort: 8443
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        args: ["start", "--https-port=8443", "--https-certificate-file=/etc/x509/https/tls.crt", "--https-certificate-key-file=/etc/x509/https/tls.key", "--hostname=132.164.68.0", "--hostname-strict=false"]
        volumeMounts:
        - name: keycloak-certs
          mountPath: /etc/x509/https
          readOnly: true
      volumes:
      - name: keycloak-certs
        secret:
          secretName: keycloak-certs