replicaCount: 1

persistence:
  enabled: true
  size: 2Gi
  storageClass: ""

rabbitmq:
  username: user
  password: password
  tls:
    enabled: false

service:
  type: ClusterIP
  port: 5672
  managementPort: 15672
