apiVersion: v1
kind: Service
metadata:
  name: pfa-project-rmq3
spec:
  type: LoadBalancer
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
    protocol: TCP
  - name: management
    port: 15672
    targetPort: 15672
    protocol: TCP
  selector:
    app: rabbitmq