apiVersion: v1
kind: ConfigMap
metadata:
  name: report-service-config
data:
  spring.application.name: "report-service"
  spring.config.import: "optional:configserver:http://configserver-service:9191/"
  LOG_LEVEL: "INFO"