apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  labels:
    app: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: microacrregistry.azurecr.io/discovery-server
        ports:
        - containerPort: 8761
        env:
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: config-server-env
                key: CONFIG_SERVER_URL